export const actionType = {
    PLUS_COUNTER: 'PLUS_COUNTER',
    MIN_COUNTER: 'MIN_COUNTER',
    SHOW_SIDEBAR: 'SHOW_SIDEBAR',
    HIDE_SIDEBAR: 'HIDE_SIDEBAR',

    INPUT_SEARCH_FLIGHT: 'INPUT_SEARCH_FLIGHT',
    SUBMIT_SEARCH_FLIGHT: 'SUBMIT_SEARCH_FLIGHT',
    GET_FLIGHT: 'GET_FLIGHT',
    FLIGHT_DETAIL: 'FLIGHT_DETAIL',

    CHANGE_DEPARTURE: 'CHANGE_DEPARTURE',
    CHANGE_ARRIVAL: 'CHANGE_ARRIVAL',
    DEPARTURE_FLIGHT: 'DEPARTURE_FLIGHT',
    RETURN_FLIGHT: 'RETURN_FLIGHT',
    USER: 'USER',
    NOTIF_COUNT: 'NOTIF_COUNT',
    RESET_INPUT: 'RESET_INPUT',
    CHANGE_FLIGHT: 'CHANGE_FLIGHT',
}