export const actionType = {
    PLUS_COUNTER: 'PLUS_COUNTER',
    MIN_COUNTER: 'MIN_COUNTER',
    SHOW_SIDEBAR: 'SHOW_SIDEBAR',
    HIDE_SIDEBAR: 'HIDE_SIDEBAR',

    INPUT_SEARCH_FLIGHT: 'INPUT_SEARCH_FLIGHT',
    SUBMIT_SEARCH_FLIGHT: 'SUBMIT_SEARCH_FLIGHT',
    GET_FLIGHT: 'GET_FLIGHT',
    FLIGHT_DETAIL: 'FLIGHT_DETAIL',
}